### ISSUE TITLE
Show hidden functions in docs

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/docs#89]
Some functions which do not have comments are hidden from the generated documentation.

Some of them are pretty relevant like `total_balance`, `ensure_can_withdraw`, etc...

We should either add simple docs to all these functions, or some flag so they are not hidden.

**Comment by bkchr** [comment]
https://crates.parity.io/srml_support/traits/trait.Currency.html they are not hidden?

**Comment by shawntabrizi** [comment]
They are hidden in the context of the Balances module:

https://crates.parity.io/srml_balances/struct.Module.html#method.ensure_can_withdraw

But still searchable there:
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/1860335/58820081-ea10cd80-8631-11e9-9f75-05019a645b0c.png">

Should we just expect users to know to click the Currency trait?

**Comment by bkchr** [comment]
If you want to know the documentation of a trait function, you need to look into the trait. That is the same behavior for each rust crate.
