### ISSUE TITLE
Website license should be Parity instead of Facebook

### ISSUE THREAD

**Issue by ltfschoen** [substrate-developer-hub/docs#95]
When I look at the Licenses used in the website code it says its copyright Facebook (i.e. https://github.com/substrate-developer-hub/docs/blob/master/website/pages/who/contract-developer.js#L2)

**Comment by JoshOrndorff** [comment]
I vote for just removing that notice entirely.

**Comment by shawntabrizi** [comment]
Yeah I need to make the whole thing Apache 2

**Comment by shawntabrizi** [comment]
I had to remove the license from the MD files since the HTML comment broke things...

Seems to be a Docusaurus bug. If we need a license on our actual docs, we will need to try something else.
